dna = "CAGGAATGGCCGAGACGATACATCGTCGGGAATAGCAGGTTCTTAGTCTCGTGCGGCTGCGTACACGCACAATCTTGAACAGACCACATGTAGGGGCCGCGATGTCAAGTACGGCTACAGTACCCATGTCGTCAGTAGCAACATGGGAAGCTATGGCACCCAATCACACGGTTCCCCCTTGAGAATAGGGATTAGGCTCTTCCCTAGCTTATTGGCATGCTGCATATTGCCATACCGTACTGAAATTAAGTGTTCGATGGCAAGGGGGTTTACCAAGATCTATGACTCTGCACATCGATGAAGGTGGATCCCGGGCTCACTCGTTCCAGATATCATCCGATGGACGTACTGGTGGATCGAAGTTTAGGGTCGTACACTTGGTTATTCGACATAACATGTTACTGGGTAACGATTGATACACCTGGATACATCAGCGACCACGCACGGGAAGGATGTGGTTATGCGAATGTTTAAATCGTATGCGGGACCTAATAAGCCTTCCATTGTAGATCTCCTTGGCCAGTTTTATAGACATAGCTAGCTGCTTACCAGAGCGACGCAATGTATGCGGAGGACCACACTCAAAAAAGACTTCGTCGGGTAGCCTTGGATTGAGGTTAGACTCCGATGACTTTCATTCCTGCGACCTGCTCAGAGTGGTGCGCAGGTTACAAGTGGAGTGGACTAAATTCCAATGAATTTGTAGCAGATAGTAACCTCAGGGAAGATAGGTCACACTTAACGGTTAAAGAAGCTCATCAGTCAGGTTAGCCTGACCGGATGAGTTTGGCCCATAATTGCAGACCGGGATTAGAATGCAATATATCGGATGGATTAGCTTTCGAGCCTTTACCGTAGGCCACGGAG"

fitaComplementar = ''
temp = ''

for c in dna:
    if c == 'A':
        temp = 'T'
        fitaComplementar = fitaComplementar + temp
    elif c == 'T':
        temp = 'A'
        fitaComplementar = fitaComplementar + temp
    elif c == 'C':
        temp = 'G'
        fitaComplementar = fitaComplementar + temp
    elif c == 'G':
        temp = 'C'
        fitaComplementar = fitaComplementar + temp

print(fitaComplementar[::-1])